### ISSUE TITLE
$HOME/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows' is not a directory!

### ISSUE THREAD

**Issue by kaiyulee** [hangxingliu/open-in-vscode-workflow#1]
```
fatal: '/Users/beke/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows' is not a directory!
```

如果大家设置了Alfred的配置文件路径，大概率会发生这个问题。
<img width="450" alt="image" src="https://user-images.githubusercontent.com/3700655/174271243-158677ec-34ab-414e-9ba8-9a1032c11581.png">

修改下 文件
`install-workflow.sh` 中的
`ALFRED4_WORKFLOWS_DIR="$HOME/Documents/AlfredSettingsSync/Alfred.alfredpreferences/workflows"` 即可

**Comment by hangxingliu** [comment]
This bug also appears when there no workflows in Alfred:

```
fatal: '/Users/noroot/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows' is not a directory!
```

**Comment by hangxingliu** [comment]
Update installer: get correct path from `prefs.json`
